version: '3'
services:
  frontend:
    build: duomusico-frontend
    ports:
     - "80:80"
#  backend:
#    build: Duolingo-e-mersion-server
#    ports: 
#     - "8002:8002"
  pythonbackend: 
    build: duomusico-python
    ports: 
     - "1235:1235"
    volumes:
      - ./duomusico-python:/myapp
